[package]
name = "app"
version = "0.2.3"
description = "Graphical User Interface for RISM"
authors = ["Julian Pollinger"]
license = "MIT"
repository = "https://github.com/neferin12/ism"
default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.1.1", features = [] }
rism = { path = "../../../rust"}
tauri-plugin-dialog = "2.0.3"
tauri-plugin-notification = "2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
bundle_z3 = ["rism/static-link-z3"]
