[package]
name = "rism"
version = "0.1.0"
edition = "2021"

[lib]
name = "librism"
path = "src/lib.rs"

[[bin]]
name = "rism"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
